-- Run this once in your Supabase project's SQL Editor (left sidebar -> SQL Editor -> New query).
-- Paste this whole file in and click "Run".

create table if not exists leaderboard_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  config_id text not null,       -- '10x10' | '15x15' | '20x20' | '25x25'
  game_type text not null,       -- 'accuracy' | 'race' | 'time_trial'
  initials text not null check (char_length(initials) = 4),
  correct_count int not null default 0,
  attempted int not null default 0,
  time_ms numeric,
  score int
);

create index if not exists idx_leaderboard_lookup
  on leaderboard_scores (config_id, game_type);

-- Row Level Security: the site has no user accounts/auth, so every visitor
-- connects as the "anon" role. These policies allow anyone to read the
-- leaderboards and insert a new score, but never update or delete existing
-- rows (so scores can't be tampered with after submission).
alter table leaderboard_scores enable row level security;

-- "drop ... if exists" first makes this script safe to paste into a fresh
-- Supabase project, or re-run on this one, without erroring on policies
-- that already exist from a previous run.
drop policy if exists "Public read access" on leaderboard_scores;
create policy "Public read access"
  on leaderboard_scores for select
  to anon
  using (true);

drop policy if exists "Public insert access" on leaderboard_scores;
create policy "Public insert access"
  on leaderboard_scores for insert
  to anon
  with check (true);

-- Explicit permission grants for the table (rather than relying on the
-- project-level "automatically expose new tables" default, which Supabase
-- itself recommends leaving off). RLS policies above control *which rows*
-- a role can see/insert; these grants are the separate, lower-level
-- permission that lets the anon role touch this table at all.
grant usage on schema public to anon, authenticated;
grant select, insert on leaderboard_scores to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;


-- =============================================================================
-- Automatic cleanup, with the all-time record always protected
-- =============================================================================
-- Rather than a hard "reset", the app treats "Monthly" and "All-time" as two
-- different queries over the same table (see js/leaderboard.js) - nothing is
-- ever physically deleted just because a month ended. This function instead
-- runs periodically as routine housekeeping, so the table doesn't grow
-- forever. It is careful to NEVER delete the current all-time-best row for
-- any config+game_type combination, no matter how old that row is - it finds
-- the best row per group FIRST, explicitly excludes it, and only then deletes
-- old rows older than 6 months from what's left.

create or replace function prune_old_leaderboard_scores()
returns void
language plpgsql
as $$
begin
  delete from leaderboard_scores t
  where t.created_at < now() - interval '6 months'
    and t.id not in (
      -- The single best row per (config_id, game_type) group, using each
      -- game type's own ranking rule (race = lowest time wins; everything
      -- else = highest score/correct_count wins). This is exactly the same
      -- "best row" that js/leaderboard.js's all-time query would return.
      select id from (
        select
          id,
          row_number() over (
            partition by config_id, game_type
            order by
              case when game_type = 'race' then time_ms end asc nulls last,
              case when game_type <> 'race' then coalesce(score, correct_count) end desc nulls last
          ) as rn
        from leaderboard_scores
      ) best_per_group
      where rn = 1
    );
end;
$$;

-- Enable the scheduler extension (safe to run even if already enabled).
create extension if not exists pg_cron with schema pg_catalog;
grant usage on schema cron to postgres;
grant all privileges on all tables in schema cron to postgres;

-- Run the cleanup at 3am UTC on the 1st of every month.
select cron.schedule(
  'prune-old-leaderboard-scores',
  '0 3 1 * *',
  $$ select prune_old_leaderboard_scores(); $$
);

-- To check the cleanup job's history later, run:
--   select jobname, status, start_time, return_message
--   from cron.job_run_details
--   order by start_time desc
--   limit 10;
