-- Run this once in your Supabase project's SQL Editor (left sidebar -> SQL Editor -> New query).
-- Paste this whole file in and click "Run".

create table if not exists leaderboard_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  config_id text not null,       -- '10x10' | '15x15' | '20x20' | '25x25'
  game_type text not null,       -- 'accuracy' | 'race' | 'time_trial'
  initials text not null check (char_length(initials) = 4),
  correct_count int not null default 0,
  attempted int not null default 0,
  time_ms numeric,
  score int
);

create index if not exists idx_leaderboard_lookup
  on leaderboard_scores (config_id, game_type);

-- Row Level Security: the site has no user accounts/auth, so every visitor
-- connects as the "anon" role. These policies allow anyone to read the
-- leaderboards and insert a new score, but never update or delete existing
-- rows (so scores can't be tampered with after submission).
alter table leaderboard_scores enable row level security;

create policy "Public read access"
  on leaderboard_scores for select
  to anon
  using (true);

create policy "Public insert access"
  on leaderboard_scores for insert
  to anon
  with check (true);
